export const Actions = {
    CHANGE_VELOCITY: 'CHANGE_VELOCITY',
    CHANGE_MODE: 'CHANGE_MODE',
    CHANGE_START_REACTIVITY: 'CHANGE_START_REACTIVITY',
    CHANGE_HEIGHT: 'CHANGE_HEIGHT',
    CHANGE_POWER: 'CHANGE_POWER',
    CHANGE_NOMINAL_POWER: 'CHANGE_NOMINAL_POWER',
    CHANGE_INTERVAL: 'CHANGE_INTERVAL',
} as const;
